application: <your application id>
version: 1
runtime: python27
api_version: 1
threadsafe: false

inbound_services:
- mail

handlers:
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img

- url: /cron/wakeup
  script: wakeup.app
  login: admin
  
- url : /task/wakeuptask
  script: wakeup_task.app
  login: admin
  
# 以下は自分のアプリケーション用のメールアドレスへと変更
- url: /_ah/mail/<your application mail>
  script: receive.app
  login: admin

- url: /
  script: index.app
  
- url: /index\.html
  script: index.app

- url: /.*
  script: index.app
