application: <your application id>
version: 1
runtime: python27
api_version: 1
threadsafe: true
handlers:

- url: /css
  static_dir: css
  
- url: /
  script: index.app
  
- url: /index\.html
  script: index.app

- url: /.*
  script: index.app

error_handlers:
  - file: html/error.html
