application: <YOUR-APPLICATION-ID>
version: 1
runtime: python27
api_version: 1
threadsafe: true

error_handlers:
- file: html/error.html

handlers:
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /map
  script: map_handler.app
  
- url: /placesjson
  script: places_json.app
  
- url: /delete
  script: deletion_handler.app

- url: /
  script: register_handler.app
  
- url: /index\.html
  script: register_handler.app
